package ai.brace;

import java.util.Objects;

public class Employee {
    public String firstName;
    public String middleInitial;
    public String lastName;
    public String socialSecurityNumber;

    public Employee(String _lastName, String _firstName, String _middleInitial, String _socialSecurityNumber) {
        firstName = _firstName;
        middleInitial = _middleInitial;
        lastName = _lastName;
        socialSecurityNumber = _socialSecurityNumber;
    }

    /*
    Q: Why does John Q Public appear twice?
    A: The two John Q Publics are different employee objects. Even though they have the same fields, they're stored
    in different memory locations, so they're not treated as equal with the default equals() and hashCode() implementations

    To fix this, I used intellij's autogenerated equals and hashCode to check ssn for employee.
    Also removed dashes from ssn for comparison purposes.
    */

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Employee employee = (Employee) o;
        return Objects.equals(stripDashes(socialSecurityNumber), stripDashes(employee.socialSecurityNumber));
    }

    @Override
    public int hashCode() {
        return Objects.hash(stripDashes(socialSecurityNumber));
    }

    private String stripDashes(String ssn) {
        return ssn == null ? null : ssn.replaceAll("[^0-9]","");
    }
}
